#ifndef VRCHAT_BUILTINS_H_
#define VRCHAT_BUILTINS_H_

#define VRCHAT_CAMERA_MODE_NORMAL 0.0
#define VRCHAT_CAMERA_MODE_VR_HANDHELD 1.0
#define VRCHAT_CAMERA_MODE_DESKTOP_HANDHELD 2.0
#define VRCHAT_CAMERA_MODE_SCREENSHOT 3.0

#define VRCHAT_MIRROR_MODE_NOT_IN_MIRROR 0.0
#define VRCHAT_MIRROR_MODE_VR 1.0
#define VRCHAT_MIRROR_MODE_DESKTOP 2.0

float _VRChatCameraMode;
float _VRChatMirrorMode;
float3 _VRChatMirrorCameraPos;

#endif // VRCHAT_BUILTINS_H_
